version: "3"

services:
  api:
    build: ./todo-api/
    volumes:
      - ./todo-api:/todo-api/app
    links: 
      - db
    ports: 
      - 8080:8080

  db:
    build: ./todo-db/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tododb
      MYSQL_USER: todoapp
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./todo-db/volumes:/var/lib/mysql
      - ./todo-db/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
